retargeting:
  type: vector
  urdf_path: roh_hand/roh_hand_left.urdf

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: [ 'if_proximal_joint', 'mf_proximal_joint', 'rf_proximal_joint', 'lf_proximal_joint',
                        'th_root_joint', 'th_proximal_joint' ]
  target_origin_link_names: [ "base","base" ,"base", "base", "base","base"]
  target_task_link_names: [ "th_distal_link" ,"thumb_tip","index_tip", "middle_tip", "ring_tip", "little_tip"]
  scaling_factor: 1.12

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [ [ 1, 1, 1, 1, 1 ,1], [ 4, 5, 10, 15, 20, 25] ]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.5
